/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>

#define  LOG_TAG    "Java2Struct"
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__)
#define  LOGW(...)  __android_log_print(ANDROID_LOG_WARN,LOG_TAG,__VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

/* Header for class com_example_java2struct_JNIUtils */

#ifndef _Included_com_example_java2struct_JNIUtils
#define _Included_com_example_java2struct_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_java2struct_JNIUtils
 * Method:    passJava2Native
 * Signature: (Lcom/example/java2struct/Persion;)V
 */
JNIEXPORT void JNICALL Java_com_example_java2struct_JNIUtils_passJava2Native
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_java2struct_JNIUtils
 * Method:    getJavaFromNative
 * Signature: ()Lcom/example/java2struct/Persion;
 */
JNIEXPORT jobject JNICALL Java_com_example_java2struct_JNIUtils_getJavaFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
